CREATE TABLE ALLIANCE
(
	AllianceName VARCHAR(20) CHECK(LEN(AllianceName)>=2) PRIMARY KEY,
	DateFormed DATE CONSTRAINT DateFormed CHECK (YEAR(DateFormed) >= 1997) --oldest alliance is from 1997
);

CREATE TABLE AIRLINE
(
	AirlineName VARCHAR(50)  CHECK(LEN(AirlineName)>=2) PRIMARY KEY,
	NetWorth DECIMAL(10,0), --max value is in billion dollar range
	AllianceName VARCHAR(20) REFERENCES ALLIANCE  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE OWNERS
(
	OwnerID  INT IDENTITY(1,1) PRIMARY KEY,
	OwnerName VARCHAR(50) NOT NULL,
	NetWorth DECIMAL(14,0), --max value is in tens trillion dollar range, how to compare value here with airline net worth
);

CREATE TABLE OWNERS_AND_AIRLINES 
(
	OwnerID INT	NOT NULL,
	AirlineName VARCHAR(50) NOT NULL,
	CONSTRAINT OwnIdent FOREIGN KEY (OwnerID) REFERENCES OWNERS ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT AirlName FOREIGN KEY (AirlineName) REFERENCES AIRLINE, 
	PRIMARY KEY (OwnerID,AirlineName) --To prevent repitition
);

CREATE TABLE ADDRESSES
(
	AddressID  int IDENTITY(1,1) PRIMARY KEY,
	City VARCHAR(85)NOT NULL,
	Street VARCHAR(85)NOT NULL,
	Country VARCHAR(60) NOT NULL,
	PostalCode VARCHAR(6) NOT NULL UNIQUE CHECK (PostalCode LIKE '[0-9][0-9]-[0-9][0-9][0-9]')
);

CREATE TABLE PRODUCER
(
	ProducerID int IDENTITY(1,1) PRIMARY KEY,
	ProducerName VARCHAR(50)  CHECK(LEN(ProducerName)>=2) UNIQUE,
	DateFormed DATE,
	AddressID int REFERENCES ADDRESSES --ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE MODEL
(
	ModelID VARCHAR(50) CHECK(LEN(ModelID)>=4) PRIMARY KEY ,
	ModelName VARCHAR(50)  CHECK(LEN(ModelName)>=2) UNIQUE,
	Price DECIMAL(11,2) NOT NULL,
	CreationDate DATE NOT NULL,
	MaxSpeed DECIMAL(3,0) NOT NULL,
	Payload DECIMAL(3,1) NOT NULL,
	PassengerCap DECIMAL(3,0) NOT NULL,
	ProducerID int REFERENCES PRODUCER ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PLANE
(
	TailNo VARCHAR(6) NOT NULL PRIMARY KEY,
	ProdYear DECIMAL(4,0) DEFAULT '9999', --How to make sure value here is >= CreationDate in Model?
	AirlineName VARCHAR(50) REFERENCES AIRLINE  ON DELETE CASCADE ON UPDATE CASCADE,
	ModelID VARCHAR(50) REFERENCES MODEL ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE AIRPORT
(	
	AirportCode VARCHAR(4) CHECK (AirportCode LIKE '[A-Z][A-Z][A-Z][A-Z]') PRIMARY KEY, --ICAO code
	AirportName VARCHAR(50) NOT NULL,
	AirportLocation VARCHAR(85) NOT NULL
);

CREATE TABLE FLIGHT
(
	FlightID VARCHAR(7) CHECK (FlightID LIKE '[A-Z][A-Z] [0-9][0-9][0-9][0-9]') PRIMARY KEY,
	DepartingApCode VARCHAR(4),
	ReceivingApCode VARCHAR(4),
	DepartureTime TIME NOT NULL,
	ArrivalTime TIME NOT NULL,
	CONSTRAINT DepApCode FOREIGN KEY (DepartingApCode) REFERENCES AIRPORT ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT RecApCode FOREIGN KEY (ReceivingApCode) REFERENCES AIRPORT ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT checkRecApCode CHECK
	(
		ReceivingApCode != DepartingApCode
	)
);

CREATE TABLE FLIGHT_AND_PLANES
(
	TailNo VARCHAR(6) NOT NULL ,
	FlightID VARCHAR(7) NOT NULL ,
	CONSTRAINT TailNum FOREIGN KEY (TailNo) REFERENCES PLANE ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FlightIdent FOREIGN KEY (FlightID) REFERENCES FLIGHT ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY (TailNo,FlightID) --To prevent repitition
);

