SELECT * FROM ALLIANCE
SELECT * FROM AIRLINE
SELECT * FROM OWNERS
SELECT * FROM OWNERS_AND_AIRLINES
SELECT * FROM ADDRESSES
SELECT * FROM PRODUCER
SELECT * FROM MODEL
SELECT * FROM PLANE
SELECT * FROM AIRPORT
SELECT * FROM FLIGHT
SELECT * FROM FLIGHT_AND_PLANES

SELECT AirlineName FROM AIRLINE WHERE AirlineName BETWEEN 'A' AND 'C'
SELECT ModelName , Price/100 AS PriceDiv100 FROM MODEL WHERE Price > 100000000
SELECT ModelName , Price FROM MODEL WHERE Price > 100000000

DROP TABLE FLIGHT_AND_PLANES
DROP TABLE FLIGHT 
DROP TABLE AIRPORT
DROP TABLE PLANE
DROP TABLE MODEL
DROP TABLE PRODUCER
DROP TABLE ADDRESSES
DROP TABLE OWNERS_AND_AIRLINES
DROP TABLE OWNERS
DROP TABLE AIRLINE
DROP TABLE ALLIANCE
DROP VIEW ModAirAllJoined


--UPDATE DELETE CASCADE on ALLIANCE
UPDATE ALLIANCE SET AllianceName = 'NewBrutus' WHERE AllianceName = 'Brutus'
DELETE FROM ALLIANCE WHERE AllianceName = 'NewBrutus'

--UPDATE DELETE CASCADE on ADDRESSES
UPDATE ADDRESSES SET City = 'Tokyo' WHERE City = 'Toyoyama'
UPDATE PRODUCER SET AddressID = 10 WHERE AddressID = 2
DELETE FROM ADDRESSES WHERE City = 'Tokyo'

DELETE FROM OWNERS WHERE OwnerName = 'First Sentier Investor' --should not delete an airline

SELECT AirlineName, COUNT(*) AS OwnerNo
FROM OWNERS_AND_AIRLINES
GROUP BY AirlineName
HAVING COUNT(*) >=2